### ISSUE TITLE
How to convert my onnx model to hailo format?

### ISSUE THREAD

**Issue by 0312birdzhang** [hailo-ai/hailo-rpi5-examples#10]
There is no downloadable tools on hailo.ai, is this not opened?

**Comment by Anguinru** [comment]
As far as I've found, you can get the conversion instructions as shown here
[hailo-ai/onnxruntime](https://github.com/hailo-ai/onnxruntime/blob/d176acc993d73455b82efcd4c1834f11e031f802/hailo/README.md)

Found a conversion sample instructions here:
[ONNX model with Hailo](https://www.macnica.co.jp/en/business/semiconductor/articles/hailo/144843/)

It seems that you need a Hailo Dev Accound to access the documentation

Hailo Repository [hailo-ai/Hailo-Application-Code-Examples](https://github.com/hailo-ai/Hailo-Application-Code-Examples?tab=readme-ov-file#hailo-application-code-examples) claims to have a conversion example but I couldn't find it under the 'model_compilation' directory

**Comment by 0312birdzhang** [comment]
@Anguinru Thank you very much, very helpful.
