### ISSUE TITLE
Data type support?

### ISSUE THREAD

**Issue by joshglens** [hailo-ai/hailo-rpi5-examples#13]
Hi all, I was wondering what data types this TPU supports. Is it only UINT8 / INT8? Or can it run FP16 / INT16 inference at a slower rate?

**Comment by giladnah** [comment]
Hailo support int8 and int16.
See more data in our developer zone https://hailo.ai/
Also you are welcome to ask questions and get more information in our [community site.](https://community.hailo.ai/)
