### ISSUE TITLE
Question about detection.py example

### ISSUE THREAD

**Issue by Gordon999** [hailo-ai/hailo-rpi5-examples#22]
The image from the rpi camera is scaled to 640 x 640 to suit the hailo, is it possible to crop a 640x640 section out of the image and use that for detection ?

**Comment by goatzillax** [comment]
I don't know if there's some accelerated/integrated version available, but you literally have all of python OpenCV (looks like an array slice) and Gstreamer (videocrop) at your disposal in the examples.  My guess is the latter would be faster.

**Comment by Gordon999** [comment]
Thanks. I'll give the gstreamer videocrop a try...

**Comment by Gordon999** [comment]
I got it to work fine.
This modification to detection.py gives me a square format by cropping left and right...

def get_pipeline_string(self):
        if (self.source_type == "rpi"):
            source_element = f"libcamerasrc name=src_0 ! " 
            source_element += f"video/x-raw, format={self.network_format}, width=1280, height=1088 ! "
            source_element += QUEUE("queue_src_scale")
            source_element += f"videocrop top=0 left=96 right=96 bottom=0 ! "
            source_element += f"videoscale ! "
            source_element += f"video/x-raw, format={self.network_format}, width={self.network_width}, height={self.network_height}, framerate=25/1 ! "
