### ISSUE TITLE
[hailo-rpi5-examples] Run the Rasberry pi 5 with Hailo 8, meet thje ninja compile file

### ISSUE THREAD

**Issue by jkllbn2563** [hailo-ai/hailo-rpi5-examples#37]
Run: ./compile_postprocess.sh 

/usr/bin/ld: cannot find -lgsthailometa: No such file or directory
/usr/bin/ld: cannot find -lhailo_tracker: No such file or directory
/usr/bin/ld: cannot find -lhailo_gst_image: No such file or directory
/usr/bin/ld: cannot find -lhailo_cv_singleton: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by chm10** [comment]
I have the same issue to run the compile_postprocess.sh.

**Comment by chm10** [comment]
I solved the compilation changing  the above parts of compilation code and after installing `rapidjson-dev`. 

```bash 
sudo apt-get install rapidjson-dev
```

**Comment by chm10** [comment]
I tested but  not worked yet. I almost sure the issue is from the environmet variables `venv_hailo_rpi5_examples`
```bash
python basic_pipelines/detection.py --help
Traceback (most recent call last):
  File "/home/user/hailo-rpi5-examples/basic_pipelines/detection.py", line 11, in <module>
    import hailo
ImportError: libgsthailometa.so.3: cannot open shared object file: No such file or directory
```

**Comment by chm10** [comment]
After reinstalling, worked. 

```bash
sudo apt-get install --reinstall hailo-tappas-core-3.28.2
```

```
python basic_pipelines/detection.py --help
usage: detection.py [-h] [--input INPUT] [--use-frame] [--show-fps] [--disable-sync] [--dump-dot] [--network {yolov6n,yolov8s,yolox_s_leaky}] [--hef-path HEF_PATH]
                    [--labels-json LABELS_JSON]

Hailo App Help

options:
  -h, --help            show this help message and exit
  --input INPUT, -i INPUT
                        Input source. Can be a file, USB or RPi camera (CSI camera module). For RPi camera use '-i rpi' (Still in Beta). Defaults to /dev/video0
  --use-frame, -u       Use frame from the callback function
  --show-fps, -f        Print FPS on sink
  --disable-sync        Disables display sink sync, will run as fast as possible. Relevant when using file source.
  --dump-dot            Dump the pipeline graph to a dot file pipeline.dot
  --network {yolov6n,yolov8s,yolox_s_leaky}
                        Which Network to use, default is yolov6n
  --hef-path HEF_PATH   Path to HEF file
  --labels-json LABELS_JSON
                        Path to costume labels JSON fil
```

**Comment by giladnah** [comment]
Hi did you install the apt hailo-all? these files should be installed by this install.

**Comment by jkllbn2563** [comment]
Yes, I have already run "sudo apt install hailo-all", but still hit the compile error

sudo apt install hailo-all
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
hailo-all is already the newest version (3.28.2+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by jkllbn2563** [comment]
sudo apt-get install --reinstall hailo-tappas-core-3.28.2

can solve the compile issue. Thanks @chm10 !
