### ISSUE TITLE
[Question] Supported DNN frameworks 

### ISSUE THREAD

**Issue by Red-Eyed** [hailo-ai/hailo-rpi5-examples#5]
Hello!

I didn't find any mentions about supported DNN frameworks like pytorch, onnxruntime, tensorflow.

Question is: how can I run custom models in onnx format (or tflite)?

Thanks.

**Comment by aallan** [comment]
I'm also interested in this, see aallan/benchmarking-ml-on-the-edge#2, I'd like to add Hailo support to my [benchmarking framework](https://github.com/aallan/benchmarking-ml-on-the-edge). That'll need my benchmark models (which are in tensorflow format) to get converted to HEF so I can used them in my scripts.

**Comment by giladnah** [comment]
Hi guys our Dataflow Compiler supports imports of models from onnx and tensorflow.
Please see documentation in our developer zone and join our [Community](https://community.hailo.ai/t/dataflow-compiler-dfc-availability/1476?u=giladnl) for support.
