### ISSUE TITLE
Hailo-8 HailoRT Error check failed .

### ISSUE THREAD

**Issue by yoyojacky** [hailo-ai/hailo-rpi5-examples#6]
![image](https://github.com/hailo-ai/hailo-rpi5-examples/assets/6893075/f05d49b4-72b7-4d72-92da-da38735d0de8)
![image](https://github.com/hailo-ai/hailo-rpi5-examples/assets/6893075/81d71f8c-72d6-4ab0-8f58-47555d718c92)

**Comment by yoyojacky** [comment]
I am using USB camera which can be used by using opencv

**Comment by yoyojacky** [comment]
![image](https://github.com/hailo-ai/hailo-rpi5-examples/assets/6893075/16ccbff3-35a0-42ac-87e7-d4c6c6a1131a)
when i change input argument to `/dev/video0`, it will show this error. 
I  am sure that the USB camera is working properly when i use opencv to test it. 
How can i solve this problem ?

**Comment by yoyojacky** [comment]
![image](https://github.com/hailo-ai/hailo-rpi5-examples/assets/6893075/4125ac5f-4419-4e6d-8fbc-a780ba90473c)

**Comment by giladnah** [comment]
See additional info here [Running with Different Input Sources](https://github.com/hailo-ai/hailo-rpi5-examples/blob/main/doc/basic-pipelines.md#running-with-different-input-sources)
